#!/bin/bash

arg1=$1
arg2=$2
arg3=$3
ipAddr=""

function fetchIP() {
    curl icanhazip.com
}

if [[ "$arg1" == "-l" || "$arg1" == "--loop" ]]; then
    echo -e "\033[0;33mRunning loop\033[0m"
    
    if [[ "$arg2" == "-c" || "$arg2" == "--count" ]]; then
        if ! [[ "$arg3" == "" ]]; then
	    for i in $(seq $arg3); do
                fetchIP
		sleep 1
            done
	fi
    else
	echo -e "\033[0;33mPress 'q' to exit\033[0m"
        while [[ true ]]; do
	    read  -rsn1 -t 0.01 input
	    if [[ $input == "q" ]]; then
		echo ""
		exit 1
	    fi
	    fetchIP
	    sleep 1
	done
    fi

else
    echo -e "\033[0;33mPinging icanhazip.com...\033[0m"
    fetchIP
fi

